apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-fullcycle
spec:
  selector: # é responsável por filtrar todos os pods que vão estar incorporados nesse serviço
    app: clean-architecture-fullcycle
  type: ClusterIP
  ports:
    - name: clean-architecture-fullcycle
      port: 8080 # é a porta que vai ser exposta pelo service
      targetPort: 3000 # é a porta do container
      protocol: TCP