name: clean-architecture-fullcycle

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run unit tests
        run: yarn test
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: lukinhasssss/node-clean-architecture-fullcycle:latest