name: clean-architecture-fullcycle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run unit tests
        run: yarn test